### ISSUE TITLE
C++/CX builds do not work with latest UWP version

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/Win2D#984]
After updating from 1.26.0 to 1.28.2, my C++/CX project no longer builds, hitting the following errors instead: :')

```
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(252,34): error C2065: 'ID2D1Device1': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(252,48): error C2065: 'device': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(252,66): error C2065: 'resource': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(252,56): error C2275: 'IUnknown': expected an expression instead of a type
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(252,22): error C2365: 'Microsoft::Graphics::Canvas::GetOrCreate': redefinition; previous definition was 'function'
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(253,13): error C2447: '{': missing function header (old-style formal list?)
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(259,34): error C2065: 'ID2D1Device1': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(259,48): error C2065: 'device': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(259,66): error C2065: 'resource': undeclared identifier
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(259,56): error C2275: 'IUnknown': expected an expression instead of a type
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(259,76): error C2062: type 'float' unexpected
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(260,13): error C2143: syntax error: missing ';' before '{'
Win2D.uwp.1.28.2\Include\Microsoft.Graphics.Canvas.native.h(260,13): error C2447: '{': missing function header (old-style formal list?)
```

(UWP, VS 17.13 Preview 5)

**Comment by getrou** [comment]
Hm, that is concerning, we'll definitely take a look at this. @Sergio0694 FYI looks like an issue with the native header.

In the meantime, as a workaround, try including d2d1_2.h before including microsoft.graphics.canvas.native.h

**Comment by JohnnyWestlake** [comment]
> Hm, that is concerning, we'll definitely take a look at this. [@Sergio0694](https://github.com/Sergio0694) FYI looks like an issue with the native header.
> 
> In the meantime, as a workaround, try including d2d1_2.h before including microsoft.graphics.canvas.native.h

That does allow it successfully build

**Comment by riverar** [comment]
Broken due to https://github.com/microsoft/Win2D/commit/2cda78a380150517e5b0064fffd18f04ae553d0b (and maybe others); this commit looks wrong and adds a dependency to a specific D2D version (1) where there wasn't one before.
